aws:
  dynamodb:
    endpoint: "http://localstack:4566"
    userTable: "userTable"
  region: "us-east-1"
  accessKey: "dummy"
  secretKey: "dummy"

spring:
  data:
    redis:
      port: 6379
      host: redis

adapter:
  dynamodb:
    userTable: "userTable"
    region: "us-east-1"