server:
  port: 8080
spring:
  application:
    name: "UserTest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: "${ENVIRONMENT:dev}"
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      port: 6379
      host: redis
logging:
  structured:
    format:
      console: "ecs"
  level:
    root: "INFO"
    '[co.com.bancolombia]': "${LOG_LEVEL:INFO}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "https://reqres.in/api"
    apiKey: "reqres-free-v1"
  dynamodb:
    userTable: "userTable"
    region: "us-east-1"
aws:
  dynamodb:
    endpoint: "http://localhost:4566"
    userTable: "userTable"
  region: "us-east-1"
  accessKey: "dummy"
  secretKey: "dummy"
